name: Build WF

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "10 * * * *"

permissions:
  contents: read

env:
  ECR_REPOSITORY: vprofileapp-img  # ✅ your ECR repo name

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Maven Build
        run: mvn clean install

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-jar
          path: target/*.jar

      - name: Notify build success
        if: success()
        run: echo "✅ Build successful!"

      - name: Notify build failure
        if: failure()
        run: echo "❌ Build failed!"

  Testing:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-jar

      - name: Run tests on main branch
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

  Security_Scans:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Trivy file scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          format: json
          exit-code: 0
          vuln-type: os,library
          output: trivy-report.json

      - name: Upload Trivy report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy-report.json

  BUILD_AND_PUBLISH:
    name: BUILD_AND_PUBLISH
    runs-on: ubuntu-latest
    needs: [Build, Testing, Security_Scans]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/
